# Generated by Django 4.2 on 2023-04-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_product_price_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='option',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
