# Generated by Django 4.2 on 2023-04-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_product_option_remove_productattribute_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
